[package]
name = "aoj-rust"
version = "0.1.0"
authors = ["Acasune <tttt4aaaa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "itp1-1-a"
path = "ITP1/ITP1-1/itp1-1-a.rs"

[[bin]]
name = "itp1-1-b"
path = "ITP1/ITP1-1/itp1-1-b.rs"

[[bin]]
name = "itp1-1-c"
path = "ITP1/ITP1-1/itp1-1-c.rs"

[[bin]]
name = "itp1-1-d"
path = "ITP1/ITP1-1/itp1-1-d.rs"
